### PR TITLE
close yaml reader after use 😰

### LINKED ISSUE #959: SCM checkout locks CasC directory
### Description

I have my CasC yaml files checked out from subversion and I would like to update them directy on Jenkins-Master by a Jenkins Pipeline-Job by using the checkout scm step from svn. Whenever the checkout needs write access, the CasC-directory becomes locked in read and write access until I restart the Jenkins. So I don't have any possibility to update the casc files on this way while the jenkins runs. Updating the CasC-directory without changes in repository works fine, but it crashes when there are files to change by the update-step.

My CasC-directory contains one yaml-file in the main-folder and additionaly some specific yaml-files inside a subfolder. All files become locked after (failing) write-access by the checkout-step. Manually updating and changing the yamls works without problems until the first checkout-attempt by the pipeline-step.

### Environment
- Jenkins LTS 2.176.2
- CasC-Plugin 1.23
- Pipeline: SCM Step Plugin 2.9
- Subversion Plugin 2.12.1
- Jenkins Master OS: Windows Server 2016 Standard

## Stacktrace

> jenkins.util.io.CompositeIOException: Unable to remove file e:\Jenkins_INT\casc\INT\env.yaml
> 	at jenkins.util.io.PathRemover.removeOrMakeRemovableThenRemove(PathRemover.java:248)
> 	at jenkins.util.io.PathRemover.tryRemoveFile(PathRemover.java:201)
> 	at jenkins.util.io.PathRemover.tryRemoveRecursive(PathRemover.java:212)
> 	at jenkins.util.io.PathRemover.tryRemoveDirectoryContents(PathRemover.java:222)
> 	at jenkins.util.io.PathRemover.tryRemoveRecursive(PathRemover.java:211)
> 	at jenkins.util.io.PathRemover.tryRemoveDirectoryContents(PathRemover.java:222)
> 	at jenkins.util.io.PathRemover.forceRemoveDirectoryContents(PathRemover.java:83)
> 	at hudson.Util.deleteContentsRecursive(Util.java:259)
> 	at hudson.Util.deleteContentsRecursive(Util.java:248)
> 	at hudson.scm.subversion.CheckoutUpdater$SubversionUpdateTask.perform(CheckoutUpdater.java:93)
> 	at hudson.scm.subversion.WorkspaceUpdater$UpdateTask.delegateTo(WorkspaceUpdater.java:168)
> 	at hudson.scm.subversion.WorkspaceUpdater$UpdateTask.delegateTo(WorkspaceUpdater.java:176)
> 	at hudson.scm.subversion.UpdateUpdater$TaskImpl.perform(UpdateUpdater.java:134)
> 	at hudson.scm.subversion.WorkspaceUpdater$UpdateTask.delegateTo(WorkspaceUpdater.java:168)
> 	at hudson.scm.SubversionSCM$CheckOutTask.perform(SubversionSCM.java:1041)
> 	at hudson.scm.SubversionSCM$CheckOutTask.invoke(SubversionSCM.java:1017)
> 	at hudson.scm.SubversionSCM$CheckOutTask.invoke(SubversionSCM.java:990)
> 	at hudson.FilePath.act(FilePath.java:1076)
> 	at hudson.FilePath.act(FilePath.java:1059)
> 	at hudson.scm.SubversionSCM.checkout(SubversionSCM.java:937)
> 	at hudson.scm.SubversionSCM.checkout(SubversionSCM.java:864)
> 	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:124)
> 	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:93)
> 	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:80)
> 	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> java.nio.file.AccessDeniedException: e:\Jenkins_INT\casc\INT\env.yaml
> 	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
> 	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
> 	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
> 	at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
> 	at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:108)
> 	at java.nio.file.Files.deleteIfExists(Files.java:1165)
> 	at jenkins.util.io.PathRemover.removeOrMakeRemovableThenRemove(PathRemover.java:233)
> 	at jenkins.util.io.PathRemover.tryRemoveFile(PathRemover.java:201)
> 	at jenkins.util.io.PathRemover.tryRemoveRecursive(PathRemover.java:212)
> 	at jenkins.util.io.PathRemover.tryRemoveDirectoryContents(PathRemover.java:222)
> 	at jenkins.util.io.PathRemover.tryRemoveRecursive(PathRemover.java:211)
> 	at jenkins.util.io.PathRemover.tryRemoveDirectoryContents(PathRemover.java:222)
> 	at jenkins.util.io.PathRemover.forceRemoveDirectoryContents(PathRemover.java:83)
> 	at hudson.Util.deleteContentsRecursive(Util.java:259)
> 	at hudson.Util.deleteContentsRecursive(Util.java:248)
> 	at hudson.scm.subversion.CheckoutUpdater$SubversionUpdateTask.perform(CheckoutUpdater.java:93)
> 	at hudson.scm.subversion.WorkspaceUpdater$UpdateTask.delegateTo(WorkspaceUpdater.java:168)
> 	at hudson.scm.subversion.WorkspaceUpdater$UpdateTask.delegateTo(WorkspaceUpdater.java:176)
> 	at hudson.scm.subversion.UpdateUpdater$TaskImpl.perform(UpdateUpdater.java:134)
> 	at hudson.scm.subversion.WorkspaceUpdater$UpdateTask.delegateTo(WorkspaceUpdater.java:168)
> 	at hudson.scm.SubversionSCM$CheckOutTask.perform(SubversionSCM.java:1041)
> 	at hudson.scm.SubversionSCM$CheckOutTask.invoke(SubversionSCM.java:1017)
> 	at hudson.scm.SubversionSCM$CheckOutTask.invoke(SubversionSCM.java:990)
> 	at hudson.FilePath.act(FilePath.java:1076)
> 	at hudson.FilePath.act(FilePath.java:1059)
> 	at hudson.scm.SubversionSCM.checkout(SubversionSCM.java:937)
> 	at hudson.scm.SubversionSCM.checkout(SubversionSCM.java:864)
> 	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:124)
> 	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:93)
> 	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:80)
> 	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)

### PR DESCRIPTION
**Pull request by casz**
fixes #959 

Not sure if there is a good way to test this. 🤔

### Your checklist for this pull request

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or in [Jenkins JIRA](https://issues.jenkins-ci.org)
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Did you provide a test-case? That demonstrates feature works or fixes the issue.

### CODE REVIEW

File: plugin/src/main/java/io/jenkins/plugins/casc/yaml/YamlSource.java [hunk 1]
```diff
@@ -16,7 +18,7 @@
  * @author <a href="mailto:nicolas.deloof@gmail.com">Nicolas De Loof</a>
  */
 
-public class YamlSource<T> {
+public class YamlSource<T> implements Closeable {
```
Comment (timja) [inline plugin/src/main/java/io/jenkins/plugins/casc/yaml/YamlSource.java]: Implement autocloseable? then we could probably use try-with-resources?

Comment (casz) [reply plugin/src/main/java/io/jenkins/plugins/casc/yaml/YamlSource.java]: How would you write a try catch block for a list?

Comment (timja) [reply plugin/src/main/java/io/jenkins/plugins/casc/yaml/YamlSource.java]: ugh

Comment (casz) [reply plugin/src/main/java/io/jenkins/plugins/casc/yaml/YamlSource.java]: I can spent more time rewriting all the code just to enable try with resources for a list of yaml sources.

Comment (casz) [reply plugin/src/main/java/io/jenkins/plugins/casc/yaml/YamlSource.java]: btw also looking through the call stack, it would be a nightmare trying to rewrite the code to.

Since there is a lot of checkWith and configureWith calling.

Lucky loooking there yamlSources go through these two closeSources should do the trick.

Comment (timja) [reply plugin/src/main/java/io/jenkins/plugins/casc/yaml/YamlSource.java]: could still implement auto-closeable for later ? you don't have to use it

**Comment by timja** [comment]
@casz this ready for merge?

**Comment by casz** [comment]
Ya, been running this PR to test file handlers don't grow out of control. Which I can confirm 😄
