### PR TITLE
fix Job DSL race condition

### LINKED ISSUE #619: Race condition for dsl job queue() and dsl script security
Hi,

I have multiple .yaml files in my CASC_JENKINS_CONFIG folder. One primarily does all the heavy lifting including disabling dsl security, e.g.:

```
security:
  globaljobdslsecurityconfiguration:
    useScriptSecurity: false
```

In a separate CASC_JENKINS_CONFIG file I am creating a seed dsl job that pulls in more dsl groovy scripts over git, e.g.:

```
jobs:
  - script: >
      pipelineJob('dsl-seed-job') {
         definition {
           cps {
             script('''node {
               stage('some_config') {
                  git branch: SOME_BRANCH, credentialsId: SOME_CREDENTIAL_ID, url: SOME_URL
                  jobDsl targets: 'job_dsl/*.groovy'
               ..................................
      }
      queue('dsl-seed-job')
```

Because this job itself executes wildcard jobDsl scripts, script security must be disabled before it is queued in order for it to run unattended.  But from the jenkins log file, it unfortunately consistently queues the job just before the script security parameter is updated, and so it fails to actually run without manual permission / intervention:

```
Oct 24, 2018 6:41:17 PM javaposse.jobdsl.plugin.JenkinsJobManagement createOrUpdateConfig
INFO: createOrUpdateConfig for dsl-seed-job
Oct 24, 2018 6:41:18 PM hudson.plugins.promoted_builds.integrations.jobdsl.PromotionsExtensionPoint notifyItemCreated
INFO: Creating promotions for dsl-seed-job
Oct 24, 2018 6:41:18 PM io.jenkins.plugins.casc.Attribute setValue
INFO: Setting javaposse.jobdsl.plugin.GlobalJobDslSecurityConfiguration@39f2b7fe.useScriptSecurity = false
```

If I go login into CasC interface within jenkins management after the container has started and hit 'Reload Existing Configuration' without making any yaml changes, the seed job successfully queues.

Is there a way to specify a prerequisite change in CasC so this doesn't happen, or enforce lexicographical filename order for yaml changes? My current workaround is to use a Datetime() delta and cron schedule the seed job to run in 1 minute which gives the config enough time to finish updating, but it feels like a sloppy workaround.

- Jenkins version 2.138.2
- Plugin version 1.11
- docker jenkins/jenkins:lts

Thanks

### PR DESCRIPTION
**Pull request by casz**
Here is our checklist for contributors. No hard requirement here, just a reminder

- [x] Please describe what you did

fixes #619 JobDSL race condition between seed job and Job DSL Script security reported

- [x] Link to issue you're working on if there's a relevant one

- [x] Did you provide a test-case to demonstrate feature actually works / issue is fixed ?

- [ ] Please also consider adding a line to [CHANGELOG.md](https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/CHANGELOG.md)

### CODE REVIEW

File: integrations/src/test/resources/io/jenkins/plugins/casc/testJob2.groovy [hunk 1]
```diff
@@ -1,12 +1,6 @@
 package io.jenkins.plugins.casc
 
 job('testJob2') {
-    scm {
-        git('git://github.com/quidryan/aws-sdk-test.git')
```
Comment (casz) [inline integrations/src/test/resources/io/jenkins/plugins/casc/testJob2.groovy]: JobDSL complains about git version number is too low.

File: integrations/src/test/resources/io/jenkins/plugins/casc/SeedJobTest_withSecurityConfig.yml [hunk 2]
```diff
@@ -0,0 +1,26 @@
...
+  - script: >
+      freeStyleJob('seedJobWithSecurityConfig') {
+        steps {
+            customWorkspace("$SEED_JOB_FOLDER_FILE_PATH")
+            dsl(['testJob2.groovy'], 'DISABLE')
+        }
+      }
+  - script: queue("seedJobWithSecurityConfig")
+
+# metrics plugin blocks build otherwise if left out
```
Comment (casz) [inline integrations/src/test/resources/io/jenkins/plugins/casc/SeedJobTest_withSecurityConfig.yml]: @batmat :see_no_evil:

Comment (timja) [reply integrations/src/test/resources/io/jenkins/plugins/casc/SeedJobTest_withSecurityConfig.yml]: umm...? 
Is that a transitive dependency of the newer job dsl plugin?

File: integrations/src/test/resources/io/jenkins/plugins/casc/testJob2.groovy (hunk 1 above)
Comment (timja) [reply integrations/src/test/resources/io/jenkins/plugins/casc/testJob2.groovy]: do we need to bump the git version instead then?

Comment (casz) [reply integrations/src/test/resources/io/jenkins/plugins/casc/testJob2.groovy]: it's inside the integrations module so 🤷‍♂️ We don't need to have more tests added when it is not needed 😄

File: integrations/src/test/resources/io/jenkins/plugins/casc/SeedJobTest_withSecurityConfig.yml (hunk 2 above)
Comment (casz) [reply integrations/src/test/resources/io/jenkins/plugins/casc/SeedJobTest_withSecurityConfig.yml]: https://github.com/jenkinsci/configuration-as-code-plugin/blob/4fd1a6990eaf4c920f714dc5ee795d78eef483cf/integrations/pom.xml#L47-L52
Metrics plugin ended up having a single integration test in our repo. 😢 Which affects build from getting assertion errors in builds and fails our integration test builds 😰

File: integrations/pom.xml [hunk 3]
```diff
@@ -221,7 +221,7 @@
     <dependency>
       <groupId>org.jenkins-ci.plugins</groupId>
       <artifactId>job-dsl</artifactId>
-      <version>1.66</version>
+      <version>1.72</version>
```
Comment (timja) [inline integrations/pom.xml]: Looks like this has a side affect of requiring jenkins version of `2.121` when the job-dsl plugin is installed.
Surprised your build passed =/

That update is fine since we were planning on updating it anyway, but a little confused

Comment (casz) [reply integrations/pom.xml]: because the integration module is already using 2.121 😄 
See https://github.com/jenkinsci/configuration-as-code-plugin/commit/4773f5e646c536f80973bc04ee7b4e46eeca25f3#diff-ad20f8808d77ba4b076cfd8eba6d97a9R15

Comment (timja) [reply integrations/pom.xml]: bahaha, well confusion solved, thanks

File: integrations/src/test/resources/io/jenkins/plugins/casc/SeedJobTest_withSecurityConfig.yml (hunk 2 above)
Comment (batmat) [reply integrations/src/test/resources/io/jenkins/plugins/casc/SeedJobTest_withSecurityConfig.yml]: o/  Not sure what is expected from me? Was I the one putting this comment? I do not remember TBH. Thanks

Comment (casz) [reply integrations/src/test/resources/io/jenkins/plugins/casc/SeedJobTest_withSecurityConfig.yml]: @batmat I added the comment since I found it odd that I would hit AssertionError: https://github.com/jenkinsci/metrics-plugin/blob/b69110b9b8115544a5b02b9709ca15df6ceab3bb/src/main/java/jenkins/metrics/api/Metrics.java#L188-L195

Running builds just because the metrics plugin installed as test dependency!

Comment (batmat) [reply integrations/src/test/resources/io/jenkins/plugins/casc/SeedJobTest_withSecurityConfig.yml]: Not sure what triggers this, not being a `metrics` plugin maintainer. I would assume something statically loads the plugin and hence fail if unconfigured or so. 

Possibly @dwnusbaum would know more about this. And if this is expected or a potential bug.

Comment (casz) [reply integrations/src/test/resources/io/jenkins/plugins/casc/SeedJobTest_withSecurityConfig.yml]: I would be keen on removing the metrics plugin test here and move it to the plugin instead 😄

Comment (casz) [reply integrations/src/test/resources/io/jenkins/plugins/casc/SeedJobTest_withSecurityConfig.yml]: I must have seen :ghost:

**Comment by casz** [comment]
codacy-bot comments turned off again, they are not helpful. I have increased pull request quality expectation instead and codacy status should fail PR.
