### PR TITLE
DataBoundConfigurator: do not throw NullPointerException with empty collection

### LINKED ISSUE #951: DataBoundConfigurator passes null to constructor when CNode is not present
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [X] Jenkins version - 2.164.1

- [X] Plugin version - 1.24-rc834.e55a938c5ddd

- [X] OS - Windows 10 1903, JDK 1.8.0_181

### Description

`DataBoundConfigurator` passes `null` to the constructor causing a `NullPointerException` when a `CNode` corresponding to a parameter is not present. See the stack trace below.
```
Caused by: io.jenkins.plugins.casc.ConfiguratorException: folderBased: Failed to construct instance of class io.jenkins.plugins.folderauth.FolderBasedAuthorizationStrategy.
 Constructor: public io.jenkins.plugins.folderauth.FolderBasedAuthorizationStrategy(java.util.Set,java.util.Set).
 Arguments: [java.util.HashSet, null].
 Expected Parameters: globalRoles java.util.Set<io.jenkins.plugins.folderauth.roles.GlobalRole>, folderRoles java.util.Set<io.jenkins.plugins.folderauth.roles.FolderRole>
    at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.tryConstructor(DataBoundConfigurator.java:168)
```

### PR DESCRIPTION
**Pull request by AbhyudayaSharma**
### Your checklist for this pull request

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [X] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!

- [X] Please describe what you did

- [x] Link to relevant GitHub issues or pull requests

- [ ] Link to relevant [Jenkins JIRA issues](https://issues.jenkins-ci.org)

- [X] Did you provide a test-case? That demonstrates feature works or fixes the issue.

### Description

When `DataBoundConfigurator` finds a collection that is not present in the `CNode`, it passes a `null` to the constructor leading to the following exception:
```
Caused by: io.jenkins.plugins.casc.ConfiguratorException: folderBased: Failed to construct instance of class io.jenkins.plugins.folderauth.FolderBasedAuthorizationStrategy.
 Constructor: public io.jenkins.plugins.folderauth.FolderBasedAuthorizationStrategy(java.util.Set,java.util.Set).
 Arguments: [java.util.HashSet, null].
 Expected Parameters: globalRoles java.util.Set<io.jenkins.plugins.folderauth.roles.GlobalRole>, folderRoles java.util.Set<io.jenkins.plugins.folderauth.roles.FolderRole>
    at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.tryConstructor(DataBoundConfigurator.java:168)
```

This pull request changes the old behavior and makes the configurator pass `Collections.emptySet()` and `Collections.emptyList()` when the parameters are known to be `Nonnull`.

@jenkinsci/gsoc2019-role-strategy 

Closes #951

### CODE REVIEW

File: plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/DataBoundConfigurator.java [hunk 1]
```diff
@@ -110,18 +113,36 @@ private T tryConstructor(Constructor<T> constructor, Mapping config, Configurati
...
             for (int i = 0; i < names.length; i++) {
                 final CNode value = config.get(names[i]);
-                if (value == null && parameters[i].getAnnotation(Nonnull.class) != null) {
-                    throw new ConfiguratorException(names[i] + " is required to configure " + target);
-                }
                 final Class t = parameters[i].getType();
+
+                if (value == null) {
+                    Class<?> clazz = constructor.getDeclaringClass();
+                    if (parameters[i].isAnnotationPresent(Required.class)) {
```
Comment (AbhyudayaSharma) [inline plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/DataBoundConfigurator.java]: I believe `org.springframework.beans.factory.annotation.Required` comes from Jenkins core and could be useful to mark parameters that are explicitly needed for configuration.

Comment (timja) [reply plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/DataBoundConfigurator.java]: I've never seen anyone use Required before =/
Nonnull and nullable are the normal ones.

Comment (oleg-nenashev) [reply plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/DataBoundConfigurator.java]: JCasC plugin already takes nullability into account in some cases, and IMHO this is the only way to get the things working without updating existing plugins. Also, Jenkins uses a very old version of Spring inside the core, and usage of its contents is not advised taking potential migration issues in the future

Comment (AbhyudayaSharma) [reply plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/DataBoundConfigurator.java]: Using `@Nonnull` should mean that the parameter we pass is not `null`; not that it is 'required'. If that's fine, we can remove the thrown exception in this case. What would you suggest here?

File: plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/DataBoundConfigurator.java [hunk 2]
```diff
@@ -24,8 +24,10 @@
 import java.util.HashSet;
 import java.util.List;
 import java.util.Set;
+import java.util.logging.Level;
 import java.util.logging.Logger;
 import javax.annotation.Nonnull;
+import javax.annotation.ParametersAreNonnullByDefault;
```
Comment (casz) [inline plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/DataBoundConfigurator.java]: Does this one not fall under JSR 305?
https://blog.codefx.org/java/jsr-305-java-9/#comment-3582702088
Would it not be better to use one from SpotBugs?
https://github.com/spotbugs/spotbugs/blob/master/spotbugs-annotations/src/main/java/edu/umd/cs/findbugs/annotations/ReturnValuesAreNonnullByDefault.java

Comment (AbhyudayaSharma) [reply plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/DataBoundConfigurator.java]: I'm not sure what you mean here. `ReturnValuesAreNonnullByDefault` seems to mean that the functions will never return `null`.

**Comment by AbhyudayaSharma** [comment]
Checking for `Nonnull` is much more complicated than what I initially thought. `Nullable` or `CheckForNull` or `ParametersAreNullable` annotations override the nonnull-ness.
 
The SonarQube test fails because the package declares a `ParametersAreNonnullByDefault` but it happily accepts a null and the getter has is annotated with `CheckForNull`. See [this](https://github.com/jenkinsci/sonarqube-plugin/blob/a42e3c460f11415356d47deb4476f83fbcb2eb42/src/main/java/hudson/plugins/sonar/SonarInstallation.java#L83-L101), [this](https://github.com/jenkinsci/sonarqube-plugin/blob/a42e3c460f11415356d47deb4476f83fbcb2eb42/src/main/java/hudson/plugins/sonar/package-info.java#L20-L21) and [this](https://github.com/jenkinsci/sonarqube-plugin/blob/a42e3c460f11415356d47deb4476f83fbcb2eb42/src/main/java/hudson/plugins/sonar/SonarInstallation.java#L206-L209). One of the options could be to pass `""` to `String` parameters. I need some suggestions on how to proceed forward.

File: plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/DataBoundConfigurator.java (hunk 2 above)
Comment (casz) [reply plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/DataBoundConfigurator.java]: Just concerned about relying on JSR 305 annotations.

File: plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/DataBoundConfigurator.java [hunk 3]
```diff
@@ -110,18 +112,38 @@ private T tryConstructor(Constructor<T> constructor, Mapping config, Configurati
...
+
+                    if (Set.class.isAssignableFrom(t)) {
+                        LOGGER.log(Level.INFO, "The parameter to be set is @Nonnull but is not present; " +
+                                                           "setting equal to empty set.");
+                        args[i] = Collections.emptySet();
+                    } else if (List.class.isAssignableFrom(t)) {
+                        LOGGER.log(Level.INFO, "The parameter to be set is @Nonnull but is not present; " +
+                                                           "setting equal to empty list.");
+                        args[i] = Collections.emptyList();
+                    } else if (String.class.isAssignableFrom(t)) {
```
Comment (AbhyudayaSharma) [inline plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/DataBoundConfigurator.java]: Will this work? It avoids the issue in the SonarQube plugin

File: plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/DataBoundConfigurator.java [hunk 4]
```diff
@@ -110,18 +112,38 @@ private T tryConstructor(Constructor<T> constructor, Mapping config, Configurati
...
             for (int i = 0; i < names.length; i++) {
                 final CNode value = config.get(names[i]);
-                if (value == null && parameters[i].getAnnotation(Nonnull.class) != null) {
-                    throw new ConfiguratorException(names[i] + " is required to configure " + target);
-                }
                 final Class t = parameters[i].getType();
+
+                Class<?> clazz = constructor.getDeclaringClass();
+                if (value == null && (parameters[i].isAnnotationPresent(Nonnull.class)   ||
+                    constructor.isAnnotationPresent(ParametersAreNonnullByDefault.class) ||
```
Comment (oleg-nenashev) [inline plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/DataBoundConfigurator.java]: May deserve a separate changelog entry. Positively impacts cases not related to collections. May deserve test automation also

File: plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/DataBoundConfigurator.java (hunk 2 above)
Comment (oleg-nenashev) [reply plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/DataBoundConfigurator.java]: I think it could be a separate improvement issue, applies to `@Nonnull` also. Maybe not only SpotBugs, but also other common annotation types.

**Comment by oleg-nenashev** [comment]
I would also say that both cases are rather improvements, not bugfixes. Guessing of annotations is just a best-effort thing for the plugin

**Comment by oleg-nenashev** [comment]
@AbhyudayaSharma is it still WiP?

**Comment by AbhyudayaSharma** [comment]
> @AbhyudayaSharma is it still WiP?

I wanted to add some tests for `@ParametersAreNonnullByDefault`, but otherwise I think it is ready.

**Comment by timja** [comment]
Thanks @AbhyudayaSharma

**Comment by oleg-nenashev** [comment]
I will manually edit the changelog after the release so that we have both changes displayed

File: plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/DataBoundConfigurator.java (hunk 3 above)
Comment (hogarthj) [reply plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/DataBoundConfigurator.java]: @AbhyudayaSharma FYI with our install after the jcasc plugin got it's update our servers are failing to start with:
```
io.jenkins.plugins.casc.ConfiguratorException: triggers is required to configure class hudson.plugins.sonar.SonarInstallation
	at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.tryConstructor(DataBoundConfigurator.java:134)
	at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.instance(DataBoundConfigurator.java:77)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:268)
	at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.check(DataBoundConfigurator.java:101)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:345)
	at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:288)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:353)
	at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:288)
	at io.jenkins.plugins.casc.ConfigurationAsCode.lambda$checkWith$6(ConfigurationAsCode.java:684)
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:646)
Caused: io.jenkins.plugins.casc.ConfiguratorException: unclassified: error configuring 'unclassified' with class 
```

Our config snippet looks like:
```
unclassified:
    sonarglobalconfiguration:
        buildWrapperEnabled: true
        installations:
        -   credentialsId: sonarqube_id
            name: our-sonarqube
            serverUrl: https://sonar.ours.url.internal
```

Comment (timja) [reply plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/DataBoundConfigurator.java]: Triggers is required, the sonar plugin needs fixing
https://github.com/SonarSource/sonar-scanner-jenkins/blob/master/src/main/java/hudson/plugins/sonar/SonarInstallation.java#L84-L92
