### PR TITLE
Role Strategy Fix + Cleanup + PermissionAssert

### LINKED ISSUE #99: Role Strategy integration - test is not fully correct
It has been noticed by @MadsNielsen and @lanwen . The reference YAML file in tests is not correct, some permissions are missed.

I should write real tests, I'd guess

### PR DESCRIPTION
**Pull request by oleg-nenashev**
- [x] Move PermissionFinder to an utility package and restrict it. I  was about using this API in Role Strategy, so I have addressed the TODO comment in the code
- [x] Fix #99 
- [x] Introduce API for checking permissions
- [x] Add tests for #99

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Tests are in progress

**Comment by oleg-nenashev** [comment]
@lanwen may want to criticize my old-style asserts instead of matchers, adding to Cc just in case

File: src/main/java/org/jenkinsci/plugins/casc/integrations/rolebasedauth/RoleDefinition.java [hunk 1]
```diff
@@ -19,20 +25,61 @@
...
+        this.role = getRole();
     }
 
-    public Role getRole() {
+    public final Role getRole() {
+        if (role == null) {
+            HashSet<String> resolvedIds = new HashSet<>();
+            for (String id : permissions) {
+                String resolvedId = PermissionFinder.findPermissionId(id);
+                if (resolvedId != null) {
```
Comment (lanwen) [inline src/main/java/org/jenkinsci/plugins/casc/integrations/rolebasedauth/RoleDefinition.java]: Objects.requireNonNull?
