### PR TITLE
Properly export floating-point values

### LINKED ISSUE #939: Floating point values are exported incorrectly
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [n/a] Jenkins version

- [x] Plugin version **1.22**

- [n/a] OS

### Description

Some plugins have floating point configuration elements. These get exported in a strange way: `someOption: !!int '12.34'`. One would expect `someOption: 12.34`.

The problem seems to be that the exporter treats all scalar values as integers:
https://github.com/jenkinsci/configuration-as-code-plugin/blob/0ce51e6111b351bb4deb8ef396a5b1944a57386c/plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCode.java#L501-L504

### PR DESCRIPTION
**Pull request by rudolfwalter**
### Your checklist for this pull request

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!

- [x] Please describe what you did

- [x] Link to relevant GitHub issues or pull requests

- [n/a] Link to relevant [Jenkins JIRA issues](https://issues.jenkins-ci.org)

- [x] Did you provide a test-case? That demonstrates feature works or fixes the issue.

### Description

Properly export floating-point values. Fixes #939.

### CODE REVIEW

File: plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCode.java [hunk 1]
```diff
@@ -494,14 +494,17 @@ public Node toYaml(CNode config) throws ConfiguratorException {
...
         }
     }
 
-    private Tag getTag(Scalar.Format format) {
-        switch (format) {
+    private Tag getTag(Scalar scalar) {
+        switch (scalar.getFormat()) {
             case NUMBER:
-                return Tag.INT;
+                if (scalar.getValue().matches("^-?[0-9]+$"))
```
Comment (casz) [inline plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCode.java]: would not be easier to match on anything with `.` in it?

Comment (rudolfwalter) [reply plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCode.java]: I thought of that, but I'm unsure if large values ever get stringified to scientific form, eg `1.3e+5` or `3e-9` (notice how the latter is a valid float that does not contain a `.`).

Comment (casz) [reply plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCode.java]: Perhaps better to add a Float/Double Format as I did for multiline? Rather than checking the value based on regex?

I'd even suggest adding the following:

```
    public Scalar(double instance) {
        this.value = String.valueOf(instance);
        this.format = Format.FLOATING;
        this.raw = true;
    }

    public Scalar(float instance) {
        this.value = String.valueOf(instance);
        this.format = Format.FLOATING;
        this.raw = true;
    }
```

Comment (rudolfwalter) [reply plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCode.java]: Yeah, adding a `FLOATING` format looks nicer to me. Should I make the change in this PR?

Comment (casz) [reply plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCode.java]: Please do :)

Comment (rudolfwalter) [reply plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCode.java]: I added some `instanceof` tests in the existing constructor taking `Number` instead of adding overloads for `Float` and `Double` because overload resolution would sometimes pick up the one you wouldn't expect.
