### PR TITLE
prefer environment variable over global config for config file path

### LINKED ISSUE #739: When config url env var changed plugin still uses old url from global config
The case:
1. There is a jenkins instance with the plugin installed running in a docker container. JENKINS_HOME directory is kept on persistent storage, so all jenkins config files are persistent.
2. CASC_JENKINS_CONFIG env variable is set up and points to https://my-config-server.com/branch1/jenkins.yaml
3. Jenkins needs to be upgraded to a new docker image. Some plugins have breaking changes so the config url should be changed as well.
4. CASC_JENKINS_CONFIG env variable changed to https://my-config-server.com/branch2/jenkins.yaml, docker container restarted with the new image.

Expected result: jenkins fetches the yaml config file from branch2.
Actual result: jenkins fetches the config file from from branch1.

As I see the reason for it is this line of code - https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCode.java#L304
```java
    private List<String> getStandardConfig() {
        List<String> configParameters = getBundledCasCURIs();
        CasCGlobalConfig casc = GlobalConfiguration.all().get(CasCGlobalConfig.class);
        String cascPath = casc != null ? casc.getConfigurationPath() : null;

        String configParameter = System.getProperty(
                CASC_JENKINS_CONFIG_PROPERTY,
                System.getenv(CASC_JENKINS_CONFIG_ENV)
        );

        if (!StringUtils.isBlank(cascPath)) {
            configParameter = cascPath;
        }
        // ....
}
```

That means if there is already a url in the global config Jenkins will never use other options like env var. It causes an issue with the case of running jenkins in docker and requires interaction with Jenkins (change the caas plugin's global config first and dump it onto the disk) in order to change the config's url (that will fail in case of breaking changes in some other plugins).

- Jenkins version - 2.150.1
- Plugin version - 1.4

### PR DESCRIPTION
**Pull request by casz**
### Your checklist for this pull request

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!

- [x] Please describe what you did

- [x] Link to relevant GitHub issues or pull requests

- [na] Link to relevant [Jenkins JIRA issues](https://issues.jenkins-ci.org)

- [x] Did you provide a test-case? That demonstrates feature works or fixes the issue.

### Description

Fixes #739 we prefer environment variable over global config, for most use cases this is the desired behavior.

### CODE REVIEW

File: plugin/src/test/java/io/jenkins/plugins/casc/ConfigurationAsCodeTest.java [hunk 1]
```diff
@@ -163,4 +166,20 @@ public void doViewExport_should_require_authentication() throws Exception {
...
+        String secondConfig = getClass().getResource("merge3.yml").toExternalForm();
+        CasCGlobalConfig descriptor = (CasCGlobalConfig) j.jenkins.getDescriptor(CasCGlobalConfig.class);
+        assertNotNull(descriptor);
+        descriptor.setConfigurationPath(firstConfig);
+        ConfigurationAsCode.get().configure();
+        Assert.assertThat(j.jenkins.getDescription(), is("configuration as code - JenkinsConfigTest"));
+        System.setProperty(CASC_JENKINS_CONFIG_PROPERTY, secondConfig);
+        ConfigurationAsCode.get().configure();
+        Assert.assertThat(j.jenkins.getDescription(), is("Configured by Configuration as Code plugin"));
+        System.clearProperty(CASC_JENKINS_CONFIG_PROPERTY);
```
Comment (reinholdfuereder) [inline plugin/src/test/java/io/jenkins/plugins/casc/ConfigurationAsCodeTest.java]: Just a minor hint: In case the test case fails before this line, but after line 180 where the system property is set, then it is still set and potentially causing side effects in other test cases... (cf. https://stefanbirkner.github.io/system-rules/ for JUnit rules reseting system properties -- maybe there is something like this also already in jenkins? or not so elegant, but easier with a simple try-finally usage)

Comment (casz) [reply plugin/src/test/java/io/jenkins/plugins/casc/ConfigurationAsCodeTest.java]: We already use system-rules I just wanted a release going we can always optimize.
Please send a PR fixing the issue.
