### PR TITLE
Deprecate misspelled Mapping.putIfNotEmpry in favor of Mapping.putIfNotEmpty

### LINKED ISSUE #1162: Mapping#putIfNotEmpry
### Description

- [ ] Please mark the incorrectly spelled method `putIfNotEmpry` deprecated 
- [ ] add new method called `putIfNotEmpty`
- [ ] old method should call new method (to avoid duplication)
- [ ] add a javadoc for old method to suggest use new method instead. (See [howto](https://stackoverflow.com/a/9031854/1103925))

The problem with IDEs is that everyone is using the autocompletion and doesn't see such misprint.

https://github.com/jenkinsci/configuration-as-code-plugin/blob/045631a8bf8b2fb0ac219128a82dca5b34716869/plugin/src/main/java/io/jenkins/plugins/casc/model/Mapping.java#L50

@ndeloof one more 🍺 for me :-)

### PR DESCRIPTION
**Pull request by bojanfilipovic**
fixes #1162

Annotated the old, misspelled method with @Deprecated and made the old method call the new one.
Link to the issue: https://github.com/jenkinsci/configuration-as-code-plugin/issues/1162

### Your checklist for this pull request

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or in [Jenkins JIRA](https://issues.jenkins-ci.org)
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Did you provide a test-case? That demonstrates feature works or fixes the issue.

### CODE REVIEW

**Comment by casz** [comment]
https://github.com/jenkinsci/configuration-as-code-plugin/pull/1163/commits/046cc3c4f2f95ba257e6179be47fdff7ff8d96fb.patch
@bojanfilipovic 
You might want to set up an email alias on your GitHub account 🥇
https://help.github.com/articles/adding-an-email-address-to-your-github-account/

Or look into fixing your git user.email config 😅  
https://help.github.com/articles/setting-your-commit-email-address-in-git
then you would need to amend your commits: https://stackoverflow.com/a/3042512
after changing author

to get proper credit for your commits 🏆

**Comment by bojanfilipovic** [comment]
Hi @casz I updated my email config to show the proper email address, let me know if all is ok now

File: plugin/src/main/java/io/jenkins/plugins/casc/model/Mapping.java [hunk 1]
```diff
@@ -47,7 +47,15 @@ public void putIfNotNull(String key, CNode node) {
         if (node != null) super.put(key, node);
     }
 
+    /**
+     * @deprecated Misspelled name, use {@link #putIfNotEmpty(String, Sequence)} instead.
+     */
+    @Deprecated
     public void putIfNotEmpry(String key, Sequence seq) {
```
Comment (timja) [inline plugin/src/main/java/io/jenkins/plugins/casc/model/Mapping.java]: should change any internal plugin calls to use the correct version

Comment (aheritier) [reply plugin/src/main/java/io/jenkins/plugins/casc/model/Mapping.java]: If there are, +1

Comment (timja) [reply plugin/src/main/java/io/jenkins/plugins/casc/model/Mapping.java]: Apparently there aren't any, just checked

The only reference to it I could find on GitHub is in the `cloudbees-jenkins-advisor-plugin` in its tests, I think we could probably just remove the method?

Comment (casz) [reply plugin/src/main/java/io/jenkins/plugins/casc/model/Mapping.java]: if no other method is referenced on GitHub I feel safe enough removing putIfNotEmpry 😄

Comment (aheritier) [reply plugin/src/main/java/io/jenkins/plugins/casc/model/Mapping.java]: Which is obviously how I found the issue :-)
Advisor isn't yet released with the JCasC integration.. Let's remove it for now I will replace by a condition on my side

**Comment by casz** [comment]
😓 Deprecate != remove 😆
