### PR TITLE
Bugfix: handling primitive types in DataBoundConfigurator.describe - fix #259

### LINKED ISSUE #259: IllegalArgumentException when instantiating a ProxyConfiguration in DataBoundConfigurator.describe on line 219
Following up on #229, we've got another error when triggering an export, when some proxy info exist on `/jenkins/pluginManager/advanced`.

Thanks @victorsalaun for spotting this :)

This is the stacktrace we got :
```
[WARNING] Error while serving http://localhost:8080/jenkins/configuration-as-code/export
java.lang.reflect.InvocationTargetException
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:347)
	at org.kohsuke.stapler.interceptor.RequirePOST$Processor.invoke(RequirePOST.java:52)
	at org.kohsuke.stapler.PreInvokeInterceptedFunction.invoke(PreInvokeInterceptedFunction.java:26)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:184)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:117)
	at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:129)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:715)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:845)
	at org.kohsuke.stapler.MetaClass$10.dispatch(MetaClass.java:374)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:715)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:845)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:135)
	at jenkins.metrics.impl.MetricsFilter.doFilter(MetricsFilter.java:125)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:138)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:90)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
	at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.jenkinsci.plugins.casc.DataBoundConfigurator.describe(DataBoundConfigurator.java:219)
	at org.jenkinsci.plugins.casc.plugins.PluginManagerConfigurator.describe(PluginManagerConfigurator.java:257)
	at org.jenkinsci.plugins.casc.plugins.PluginManagerConfigurator.describe(PluginManagerConfigurator.java:49)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.doExport(ConfigurationAsCode.java:232)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:625)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:343)
	... 63 more
```

### PR DESCRIPTION
**Pull request by Lucas-C**

### CODE REVIEW

File: src/main/java/org/jenkinsci/plugins/casc/ConfigurationAsCode.java [hunk 1]
```diff
@@ -238,22 +238,28 @@ public void doExport(StaplerRequest req, StaplerResponse res) throws Exception {
         }
 
         MappingNode root = new MappingNode(Tag.MAP, tuples, BLOCK.getStyleBoolean());
+        serializeYamlNode(root, new OutputStreamWriter(res.getOutputStream(), StandardCharsets.UTF_8));
```
Comment (ndeloof) [inline src/main/java/org/jenkinsci/plugins/casc/ConfigurationAsCode.java]: Doing so we won't benefit the try-with-resource to close the stream.

File: src/test/java/org/jenkinsci/plugins/casc/PluginManagerConfiguratorTest.java [hunk 2]
```diff
@@ -24,4 +31,51 @@ public void testInstallPlugins() {
...
+
+    @Test
+    @ConfiguredWithCode("ProxyConfigTest.yml")
+    public void describeProxyConfig() throws Exception {
+        final PluginManagerConfigurator root = getPluginManagerConfigurator();
+        final CNode configNode = root.describe(root.getTargetComponent());
+        ((Mapping) configNode).remove("sites");
+        final String yamlConfig = toYamlString(configNode);
+        assertEquals(String.join("\n",
+                "proxy:",
```
Comment (ndeloof) [inline src/test/java/org/jenkinsci/plugins/casc/PluginManagerConfiguratorTest.java]: I don't think we can guarantee the attribute ordering exported in yaml, can we ? Assert on CNode is more predictible afaik

File: src/main/java/org/jenkinsci/plugins/casc/DataBoundConfigurator.java [hunk 3]
```diff
@@ -248,4 +246,9 @@ public String getDisplayName() {
         final Descriptor descriptor = getDescriptor();
         return descriptor != null ? descriptor.getDisplayName() : "";
     }
+
+    private static <T> T getDefaultValue(Class<T> clazz) {
+        // Recipe from: https://stackoverflow.com/a/38243203/636849
+        return (T) Array.get(Array.newInstance(clazz, 1), 0);
```
Comment (ndeloof) [inline src/main/java/org/jenkinsci/plugins/casc/DataBoundConfigurator.java]: see com.google.common.base.Defaults#defaultValue

**Comment by ndeloof** [comment]
https://github.com/jenkinsci/configuration-as-code-plugin/pull/258 has been merge, can you please only include the relevant commit in this PR ?

File: src/test/java/org/jenkinsci/plugins/casc/PluginManagerConfiguratorTest.java (hunk 2 above)
Comment (Lucas-C) [reply src/test/java/org/jenkinsci/plugins/casc/PluginManagerConfiguratorTest.java]: Experimentally, it is always alphabetically sorted.
Is that OK ? I can try to find the relevant `snakeyaml` code or spec that explictely ensure this.
IHMO the benefit in terms of clarity for the tests is worth it.

File: src/main/java/org/jenkinsci/plugins/casc/DataBoundConfigurator.java (hunk 3 above)
Comment (Lucas-C) [reply src/main/java/org/jenkinsci/plugins/casc/DataBoundConfigurator.java]: Thanks, I'm going to use this

File: src/main/java/org/jenkinsci/plugins/casc/ConfigurationAsCode.java (hunk 1 above)
Comment (Lucas-C) [reply src/main/java/org/jenkinsci/plugins/casc/ConfigurationAsCode.java]: Silly me :) I'm fixing this

**Comment by Lucas-C** [comment]
Done !

File: src/main/java/org/jenkinsci/plugins/casc/ConfigurationAsCode.java [hunk 4]
```diff
@@ -238,22 +238,28 @@ public void doExport(StaplerRequest req, StaplerResponse res) throws Exception {
...
         MappingNode root = new MappingNode(Tag.MAP, tuples, BLOCK.getStyleBoolean());
+        try (Writer writer = new OutputStreamWriter(res.getOutputStream(), StandardCharsets.UTF_8)) {
+            serializeYamlNode(root, writer);
+        } catch (IOException e) {
+            throw new YAMLException(e);
+        }
+    }
+
+    // public only for testing
+    public static void serializeYamlNode(Node root, Writer writer) throws IOException {
```
Comment (oleg-nenashev) [inline src/main/java/org/jenkinsci/plugins/casc/ConfigurationAsCode.java]: Then use `@Restricted(NoExternalUse.class)`. It will prevent other plugins from using this API

File: src/main/java/org/jenkinsci/plugins/casc/ConfigurationAsCode.java [hunk 5]
```diff
@@ -238,22 +238,28 @@ public void doExport(StaplerRequest req, StaplerResponse res) throws Exception {
...
+        Serializer serializer = new Serializer(new Emitter(writer, options), new Resolver(),
+                options, null);
+        serializer.open();
+        serializer.serialize(root);
+        serializer.close();
     }
 
-    private @CheckForNull Node toYaml(CNode config) throws ConfiguratorException {
+    // public only for testing
+    public @CheckForNull Node toYaml(CNode config) throws ConfiguratorException {
```
Comment (oleg-nenashev) [inline src/main/java/org/jenkinsci/plugins/casc/ConfigurationAsCode.java]: same

File: src/test/java/org/jenkinsci/plugins/casc/PluginManagerConfiguratorTest.java (hunk 2 above)
Comment (ndeloof) [reply src/test/java/org/jenkinsci/plugins/casc/PluginManagerConfiguratorTest.java]: this is not snakeYaml but `toYaml` which translates exported `CNode`s into yaml. snakeyaml mapping's tuples are ordered, but I don't think we can guarantee ordering for the Mapping CNode (based on HashMap.entrySet), but relying on implementation details (maybe implementation specific ?).
Or maybe we could have `toYaml` sort tuples by key name to become fully deterministic.

Comment (ndeloof) [reply src/test/java/org/jenkinsci/plugins/casc/PluginManagerConfiguratorTest.java]: i.e in org.jenkinsci.plugins.casc.ConfigurationAsCode#toYaml use
```java
final List<Map.Entry<String, CNode>> entries = new ArrayList<>(mapping.entrySet());
                Collections.sort(entries, new Comparator<Map.Entry<String, CNode>>() {
                    @Override
                    public int compare(Map.Entry<String, CNode> o1, Map.Entry<String, CNode> o2) {
                        return o1.getKey().compareTo(o2.getKey());
                    }
                });
                for (Map.Entry<String, CNode> entry : entries) {
```

File: src/main/java/org/jenkinsci/plugins/casc/ConfigurationAsCode.java (hunk 4 above)
Comment (ndeloof) [reply src/main/java/org/jenkinsci/plugins/casc/ConfigurationAsCode.java]: package private should be enough anyway

Comment (Lucas-C) [reply src/main/java/org/jenkinsci/plugins/casc/ConfigurationAsCode.java]: I made it package private

File: src/main/java/org/jenkinsci/plugins/casc/ConfigurationAsCode.java (hunk 5 above)
Comment (Lucas-C) [reply src/main/java/org/jenkinsci/plugins/casc/ConfigurationAsCode.java]: I made it package private

File: src/test/java/org/jenkinsci/plugins/casc/PluginManagerConfiguratorTest.java (hunk 2 above)
Comment (Lucas-C) [reply src/test/java/org/jenkinsci/plugins/casc/PluginManagerConfiguratorTest.java]: OK, I see.
Thanks for the explanation and code snippet !
I made the change, ponly slightly shorter thanks to IntelliJ advices :)

**Comment by Lucas-C** [comment]
Just note that the test in this PR won't pass currently, cf. the issue with `ProxyConfiguration` missing descriptors described in #259
In the meantime, as the fix does not seem to be in casc, I can simply remove thos 3 problematic properties from the test.
